changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Security and correctness
      labels:
        - security
        - bug
    - title: Features
      labels:
        - enhancement
    - title: Documentation
      labels:
        - documentation
    - title: Dependencies
      labels:
        - dependencies
    - title: Other changes
      labels:
        - "*"
